//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pansiyonOtomasyonuV1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pansiyonEntities : DbContext
    {
        public pansiyonEntities()
            : base("name=pansiyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLmusteriler> TBLmusteriler { get; set; }
        public virtual DbSet<TBLcalisanlar> TBLcalisanlar { get; set; }
        public virtual DbSet<TBLalisveris> TBLalisveris { get; set; }
        public virtual DbSet<TBLfaturalar> TBLfaturalar { get; set; }
    }
}
