//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pansiyonOtomasyonuV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLalisveris
    {
        public int girisID { get; set; }
        public Nullable<decimal> domates { get; set; }
        public Nullable<decimal> patates { get; set; }
        public Nullable<decimal> sogan { get; set; }
        public Nullable<decimal> peynir { get; set; }
        public Nullable<byte> ekmek { get; set; }
        public Nullable<decimal> salatalik { get; set; }
        public Nullable<decimal> bal { get; set; }
        public Nullable<decimal> recel { get; set; }
        public Nullable<decimal> tereyag { get; set; }
        public Nullable<byte> yumurta { get; set; }
        public System.DateTime girisTarihi { get; set; }
        public int toplamTutar { get; set; }
    }
}
