//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pansiyonOtomasyonuV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLcalisanlar
    {
        public int calisanID { get; set; }
        public string calisanAdi { get; set; }
        public string calisanSoyadi { get; set; }
        public Nullable<short> calisanMaasi { get; set; }
        public string calisanPozisyon { get; set; }
    }
}
