//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pansiyonOtomasyonuV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLfaturalar
    {
        public int faturaID { get; set; }
        public string faturaAdi { get; set; }
        public decimal faturaTutari { get; set; }
        public System.DateTime faturaTarihi { get; set; }
    }
}
